name: Publish to npm
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate unique version
        id: unique_version
        run: |
          # Get the current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Generate a timestamp in the format YYMMDD.HHMM for better semver compatibility
          TIMESTAMP=$(date +'%y%m%d.%H%M')

          # Create a unique version with timestamp
          NEW_VERSION="1.0.${TIMESTAMP}"

          # Update package.json with the new version
          npm version $NEW_VERSION --no-git-tag-version

          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
