name: Publish to npm
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate unique version
        id: unique_version
        run: |
          # Generate a unique version using current date, time and run ID
          UNIQUE_SUFFIX=$(date +'%y%m%d%H%M')
          CURRENT_VERSION=$(node -p "require('./package.json').version.split('.').slice(0, 2).join('.')")
          NEW_VERSION="${CURRENT_VERSION}.${UNIQUE_SUFFIX}"

          # Update package.json with new version
          npm version $NEW_VERSION --no-git-tag-version

          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
