name: Publish to npm
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Debug package version
        run: |
          echo "Package version in package.json:"
          cat package.json | grep version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build package
        run: npm run build

      - name: Set new version
        run: |
          # Increment patch version
          npm version patch --no-git-tag-version
          # Display new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "Updated to version: $NEW_VERSION"

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
